# coding=utf-8
"""
Django settings for test01 project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b+i62$&b=fdix@l3oo%t+6o(#%@y*u#7l+iu#!p16j!v2cdh^#'

# SECURITY WARNING: don't run with debug turned on in production!
# debug模式下,浏览器界面会直接显示代码里的错误而不是404、500等页面
DEBUG = True

# 设置允许访问的主机
ALLOWED_HOSTS = ["*"]
# APPEND_SLASH = False


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',  # 使用django-admin startproject创建的项目默认启用session
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 添加新建的app激活模型
    'booktest',
)

# 配置django中间件
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # 添加自定义中间件
    # 'test01.myexc.MyException',
)

ROOT_URLCONF = 'test01.urls'

# 设置django模板
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 设置project中存放模板的路径
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'test01.wsgi.application'

# 存储session
# SESSION_ENGINE='django.contrib.sessions.backends.db'  # 默认存db,是经过base64加密的值
# SESSION_ENGINE='django.contrib.sessions.backends.cache'
# SESSION_ENGINE='django.contrib.sessions.backends.cached_db'

# 将session存入redis
# pip install django-redis-sessions
# SESSION_ENGINE = 'redis_sessions.session'
# SESSION_REDIS_HOST = 'localhost'
# SESSION_REDIS_PORT = 6379
# SESSION_REDIS_DB = 0
# SESSION_REDIS_PASSWORD = ''
# SESSION_REDIS_PREFIX = 'session'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'test01',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '192.168.233.11',
        'PORT': '3306',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-Hans'  # 修改语言

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'  # 修改时区

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# 配置静态文件地址
STATIC_URL = '/static/'  # 此处的static是逻辑路径,名字随便写可以隐藏真实路径
STATICFILES_DIRS = os.path.join(BASE_DIR, 'static')  # 这个才是真实路径
# 配置上传图片地址
MEDIA_ROOT = os.path.join(BASE_DIR, 'static/media/')

